apiVersion: apps/v1
kind: Deployment
metadata:
  name: analyzer
  namespace: sentenial
  labels:
    app: analyzer
spec:
  replicas: 2   # adjust for load
  selector:
    matchLabels:
      app: analyzer
  template:
    metadata:
      labels:
        app: analyzer
    spec:
      containers:
        - name: analyzer
          image: sentenialx/analyzer:latest   # <-- replace with your registry/image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: sentenial-config
            - secretRef:
                name: sentenial-secrets
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
      restartPolicy: Always
