# infra/k8s/apps/cortex-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cortex
  namespace: sentenial
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cortex
  template:
    metadata:
      labels:
        app: cortex
    spec:
      containers:
        - name: cortex
          image: sentenialx/cortex:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: sentenial-config
            - secretRef:
                name: sentenial-secrets
