apiVersion: apps/v1
kind: Deployment
metadata:
  name: gui
  namespace: sentenial
  labels:
    app: gui
spec:
  replicas: 2   # scale GUI horizontally if needed
  selector:
    matchLabels:
      app: gui
  template:
    metadata:
      labels:
        app: gui
    spec:
      containers:
        - name: gui
          image: sentenialx/gui:latest   # <-- replace with your actual registry/image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000        # typical React/Vue/Next.js frontend port
          envFrom:
            - configMapRef:
                name: sentenial-config
            - secretRef:
                name: sentenial-secrets
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
      restartPolicy: Always
