apiVersion: apps/v1
kind: Deployment
metadata:
  name: models
  namespace: sentenial
  labels:
    app: models
spec:
  replicas: 1   # usually heavier workloads, scale with GPUs if needed
  selector:
    matchLabels:
      app: models
  template:
    metadata:
      labels:
        app: models
    spec:
      containers:
        - name: models
          image: sentenialx/models:latest   # <-- replace with actual registry/image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: sentenial-config
            - secretRef:
                name: sentenial-secrets
          resources:
            requests:
              cpu: "500m"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
              nvidia.com/gpu: 1   # <-- uncomment if GPU inference required
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
      restartPolicy: Always
