# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"                       # Location of requirements.txt
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"           # bump both direct & transitive deps
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"
    rebase-strategy: "auto"

  - package-ecosystem: "github-actions"
    directory: "/"                       # Location of your workflow files
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
    open-pull-requests-limit: 5
    labels:
      - "automation"
    commit-message:
      prefix: "ci"
    rebase-strategy: "auto"
