# Base directories
base_dir: "/home/user/sentenial_pentest"
log_dir: "logs"
report_dir: "reports"
payloads_dir: "payloads"

# Network scanning defaults
scan_timeout: 10           # seconds
scan_retries: 3
default_ports:
  - 22
  - 80
  - 443
  - 8080

# Exploit execution defaults
max_concurrent_exploits: 5

# API configuration
api_host: "0.0.0.0"
api_port: 8080

# Logging
log_level: "INFO"

# Credential storage
credential_store_path: "credentials.json"

# Timeout for exploit scripts in seconds
exploit_timeout: 60

# Verbose/debug mode
verbose: false

# Scan depth
max_scan_depth: 3
