model_name: "threat_semantics"
registry_root: "~/.sentenialx/registry"
artifacts_root: "sentenialx/models/artifacts"

teacher_base_model: "sentenialx/models/base/threat_teacher.pt"  # replace with real
data_dir: "data/threat_corpus"                                   # replace with real

versioning:
  strategy: "patch"   # major|minor|patch
  channel: "stable"   # stable|beta|dev

distill:
  enabled: true

lora:
  enabled: true
