# docker-compose.yml (dev)
version: "3.8"
services:
  api-gateway:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENV=development
      - JWT_SECRET=dev-secret-change-me
      - FRONTEND_ORIGINS=http://localhost:3000
    volumes:
      - ./app:/app/app