#!/usr/bin/env python3
"""
Sentenial-X :: Alert Dispatcher
================================

Purpose:
    Dispatch alerts generated by Cortex, ZeroDayPredictor, or Countermeasure Agent
    to multiple destinations in a structured and auditable way.
"""

import json
import os
from datetime import datetime
from typing import Dict, List, Optional

# Example external integrations
try:
    import smtplib
    from email.mime.text import MIMEText
except ImportError:
    smtplib = None

try:
    import requests
except ImportError:
    requests = None


# ------------------------------------------------------------
# Alert Dispatcher
# ------------------------------------------------------------
class AlertDispatcher:
    def __init__(self, log_dir: str = "data/logs/alerts/"):
        os.makedirs(log_dir, exist_ok=True)
        self.log_dir = log_dir
        self.destinations: List[Dict] = []  # e.g., [{"type": "email", ...}, {"type": "slack", ...}]

    # --------------------------------------------------------
    # Register a destination
    # --------------------------------------------------------
    def register_destination(self, destination: Dict):
        """
        destination example:
        {
            "type": "email",
            "recipients": ["secops@example.com"],
            "sender": "alerts@sentenialx.com",
            "smtp_server": "smtp.example.com",
            "smtp_port": 587
        }
        OR
        {
            "type": "slack",
            "webhook_url": "https://hooks.slack.com/services/..."
        }
        """
        self.destinations.append(destination)

    # --------------------------------------------------------
    # Dispatch a single alert
    # --------------------------------------------------------
    def dispatch_alert(self, alert: Dict[str, any], priority: str = "medium"):
        """
        alert: dict containing
            - title
            - message
            - source
            - severity
            - context (optional)
        """
        # Timestamp
        alert["timestamp"] = datetime.utcnow().isoformat()
        alert["priority"] = priority

        # 1️⃣ Log locally
        self._log_alert(alert)

        # 2️⃣ Send to registered destinations
        for dest in self.destinations:
            if dest["type"] == "email":
                self._send_email(alert, dest)
            elif dest["type"] == "slack":
                self._send_slack(alert, dest)
            # extend with SIEM, webhook, SMS, etc.

    # --------------------------------------------------------
    # Internal: log alert
    # --------------------------------------------------------
    def _log_alert(self, alert: Dict):
        filename = f"{datetime.utcnow().isoformat().replace(':','-')}_{alert.get('source','unknown')}.json"
        path = os.path.join(self.log_dir, filename)
        with open(path, "w") as f:
            json.dump(alert, f, indent=4)

    # --------------------------------------------------------
    # Internal: send email
    # --------------------------------------------------------
    def _send_email(self, alert: Dict, dest: Dict):
        if smtplib is None:
            print("[WARNING] smtplib not installed; cannot send email.")
            return
        try:
            msg = MIMEText(alert["message"])
            msg["Subject"] = f"[{alert.get('severity', 'medium').upper()}] {alert.get('title')}"
            msg["From"] = dest["sender"]
            msg["To"] = ", ".join(dest["recipients"])

            with smtplib.SMTP(dest["smtp_server"], dest.get("smtp_port", 587)) as server:
                server.starttls()
                if "username" in dest and "password" in dest:
                    server.login(dest["username"], dest["password"])
                server.send_message(msg)
        except Exception as e:
            print(f"[ERROR] Failed to send email alert: {e}")

    # --------------------------------------------------------
    # Internal: send slack
    # --------------------------------------------------------
    def _send_slack(self, alert: Dict, dest: Dict):
        if requests is None:
            print("[WARNING] requests not installed; cannot send Slack alerts.")
            return
        payload = {
            "text": f"*[{alert.get('severity','medium').upper()}]* {alert.get('title')}\n{alert.get('message')}"
        }
        try:
            requests.post(dest["webhook_url"], json=payload, timeout=5)
        except Exception as e:
            print(f"[ERROR] Failed to send Slack alert: {e}")


# ------------------------------------------------------------
# CLI Interface
# ------------------------------------------------------------
if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Sentenial-X Alert Dispatcher CLI")
    parser.add_argument("--alert", required=True, help="JSON string for alert")
    args = parser.parse_args()

    alert = json.loads(args.alert)
    dispatcher = AlertDispatcher()
    dispatcher.dispatch_alert(alert)
