threat_id: APT-StealthRecon-Î©
stages:
  initial_access:
    trigger: phishing_macro.docm
    method: obfuscated_base64_powershell
  delivery:
    url: https://cdn-secureapi.org/fetchstage
    beacon_type: cobalt
  privilege_escalation:
    tools: [Rubeus_sim, Mimikatz_sim]
    technique: token_impersonation
  lateral_movement:
    method: SMB_relay
    detection: auth_failures + WinRM spikes
  exfiltration:
    fake_endpoint: https://omega-clouddrop.biz/data
    archive_format: AES256_zip
    impact: file_rename + note_drop