---
# Exploit Chaining Runbook for Sentenial X Pentest Suite

name: Exploit Chaining Campaign
description: >
  Multi-stage penetration test scenario chaining initial access,
  privilege escalation, and persistence exploits.

stages:
  - name: Initial Access
    description: >
      Use a known RCE vulnerability in web server to gain shell access.
    target: webserver.example.com
    tools:
      - name: rce_exploit.py
        type: script
        path: ../../exploits/rce_exploit.py
    parameters:
      target_port: 8080
      payload: reverse_shell
    post_actions:
      - verify_shell
      - establish_persistence

  - name: Privilege Escalation
    description: >
      Exploit local kernel vulnerability to escalate from user to root.
    target: compromised_host
    prerequisites:
      - Initial Access
    tools:
      - name: kernel_escalate.py
        type: script
        path: ../../exploits/kernel_escalate.py
    parameters:
      exploit_timeout: 60
    post_actions:
      - verify_root
      - cleanup_logs

  - name: Persistence
    description: >
      Deploy backdoor service to maintain long-term access.
    target: compromised_host
    prerequisites:
      - Privilege Escalation
    tools:
      - name: backdoor_install.sh
        type: script
        path: ../../exploits/backdoor_install.sh
    parameters:
      service_name: sneaky_service
    post_actions:
      - verify_service_running

verification_steps:
  - name: verify_shell
    command: "whoami"
    expected_output: "www-data"

  - name: verify_root
    command: "id -u"
    expected_output: "0"

  - name: verify_service_running
    command: "systemctl status sneaky_service"
    expected_output_contains: "active (running)"

notes:
  - Ensure all tools are executed with proper error handling.
  - Clean up temporary files to avoid detection.
  - Log all outputs for post-mortem analysis.

