---
# Reconnaissance Runbook for Sentenial X Pentest Suite

name: Reconnaissance Campaign
description: >
  Conducts initial network and host discovery, service enumeration, and
  vulnerability scanning to map the attack surface.

stages:
  - name: Network Scan
    description: >
      Perform active network scanning to identify live hosts and open ports.
    target: network_range
    tools:
      - name: nmap_scan.py
        type: script
        path: ../../scanner/nmap_scan.py
    parameters:
      scan_type: "SYN"
      ports: "1-65535"
      timeout: 300
    post_actions:
      - parse_scan_results

  - name: Service Enumeration
    description: >
      Enumerate services on identified hosts to gather detailed information.
    target: discovered_hosts
    prerequisites:
      - Network Scan
    tools:
      - name: service_enum.py
        type: script
        path: ../../scanner/service_enum.py
    parameters:
      protocols: ["http", "ssh", "ftp", "smtp"]
    post_actions:
      - analyze_service_info

  - name: Vulnerability Scanning
    description: >
      Run vulnerability scans on enumerated services using known signatures.
    target: discovered_hosts
    prerequisites:
      - Service Enumeration
    tools:
      - name: vuln_scan.py
        type: script
        path: ../../scanner/vuln_scan.py
    parameters:
      severity_level: "medium"
    post_actions:
      - report_vulnerabilities

verification_steps:
  - name: parse_scan_results
    action: parse
    file: "./session_data/nmap_results.xml"
    criteria:
      hosts_found: ">0"
      open_ports: ">0"

  - name: analyze_service_info
    action: parse
    file: "./session_data/service_info.json"
    criteria:
      critical_services: ["ssh", "http", "rdp"]

  - name: report_vulnerabilities
    action: generate_report
    file: "./session_data/vuln_report.json"
    severity_threshold: "medium"

notes:
  - Use timing options on scanners to avoid detection.
  - Validate discovered hosts before further exploitation.
  - Save all raw output for audit and analysis.

