apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - configmap.yaml
  - secret.yaml
  - pdb.yaml
  - perglass.yaml
namespace: sentenialx
images:
  - name: sentenialx
    newName: your-registry/sentenialx
    newTag: v2.0
