site_name: Sentenial-X
site_description: Autonomous Cybersecurity Platform with AI Threat Emulation and Semantic Analysis
site_author: Sentenial Labs
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
nav:
  - Home: index.md
  - Overview: overview.md
  - Architecture: architecture.md
  - Installation: installation.md
  - CLI: cli.md
  - API Reference: api.md
  - Core Modules: core_modules.md
  - Playbooks & Simulators: playbooks.md
  - Telemetry: telemetry.md
  - Contributing: contributing.md
  - FAQ: faq.md
  - Changelog: changelog.md
  - License: license.md
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.tabbed
extra_css:
  - assets/css/custom.css
extra_javascript:
  - assets/js/custom.js
plugins:
  - search
  - mkdocs-pdf-export-plugin
