model:
  base: "mistral-7b"
  lora_path: "models/lora-adapter"
  quantize_bits: 4

http_encoder:
  pretrained: "distilbert-base-uncased"
  embed_dim: 384

server:
  host: "0.0.0.0"
  port: 8000
  max_batch_size: 4
  max_new_tokens: 256

