name: Build & Package CentennialX

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller pytest

      - name: Run tests
        run: pytest

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --windowed gui/hub.py

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: CentennialX-${{ matrix.os }}
          path: dist/*